# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_manage', '0002_auto_20171121_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerinfo',
            options={'verbose_name_plural': '电脑信息'},
        ),
        migrations.AlterModelOptions(
            name='computertype',
            options={'verbose_name_plural': '电脑类型'},
        ),
        migrations.AlterModelOptions(
            name='departmenttype',
            options={'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(to='pc_manage.ComputerInfo'),
        ),
    ]
